language: node_js
node_js:
- 4.4.0
- 5.5.0
- node
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  codeclimate:
    repo_token:
    - secure: CODECLIMATE_REPO_TOKEN
install:
- npm install
- npm install -g codeclimate-test-reporter
after_success:
- make bench
- npm run coveralls
- bash <(curl -s https://codecov.io/bash)
- codeclimate-test-reporter < ./coverage/lcov.info
- bash ./misc/deploy.sh
notifications:
  slack: cheddarlang:9RXf81jwP9LXRVyrcPPXX1vO
deploy:
  provider: npm
  email: contact@vihan.org
  api_key:
    secure: mim2vRx2fXEhN07PmuTn4aZQ6EaDh4Ji0riZZIIXvgeUVYvYoY4MJSezjTRcZIHb+gyuFvEQmLE7ILWvNzykGuv/h9c55kNPjnVgCJS8hqyNiSj3e51+d3xBLHLbemNbuvxyg1loWYL0+y8Fy2nwYBZpud3TUhZs1367W5+BLy1YVg2azYWbrVIpaXwwZH7MHFdkXYbdUxm7qaQ0dTtsGY1XgWVSAjqwFLtgVnDoTX5R7SICgnrHH+/bUynkkr/H4zHAFcu5axegFh0nIDRTXZiYxuCnNqsEu3+5ZJKWrvn2DLrEQks4/ueTqR5QgCR+rC+H7lmMacfeKH7c26p1RQuvg7Q+TCk22iFJLsJDQugoqxYKRhooMik7Cu0mVA1Tt0RWmjvVTUQEIDjNQ7h7P6R2XrAfa+sKTOZ/MfCCBICw0W0JfAao8am3IJZs7cTo+Aoqwrhw6/w+KQ+OU+KNoq18hJThyy4J6FtC+4jqJqVj6Hrr0Z6YRDooAOMY+1r/TYy8QPn0luya/RRHNelFteBzygYirbyUQRddpeju0ekwEGsRrdaa54QgPxG06YUCBo8M/A/NDFX9Kyj4d3UZMTINfIX9iv9yGrb/716z9Vr6aubqwzzfmHei23gbUimzV3OHnDphqPqOXJdNOE22TFCxQ2boiZrKtFv/L3wID7I=
  on:
    tags: true
    repo: cheddar-lang/Cheddar
    branch: master
