language: node_js
node_js:
- 4.4.0
before_script:
- npm install grunt-cli -g
deploy:
  provider: heroku
  api_key:
    secure: Rpxf/rES7lfxegHGfSI7GgZY6hcDZbjio4CoPMd4hcq6GPNAViDznNdzTcYrU/cz53IY8Whr7qArYadBSwAjLr+oXgXydenUepX4+JQ+JUs7cIJaEhvVr21X5x+yCptWr3Sep3MdG3hIInsP1VWX12kUUN6tvfu4xOjNGw0/BfxDbrw5pwRSeWZHfCSz+81oqXLqx3YuDmAvugYuJsog31lqRu9w9X5Vr9Hz446IYMywq9B9tLuuSU1aZ6rNIZdYEdToJUu0KNv0EF4fsSwOFGx1s6WG5CTPhS14oAZZkCz6ZwAiXcyIy/51WAWkG/OqC9D1R2CE73OVH+U+fvW0AuXahOZJPzfeUoIJLb6uqkiTZc2c4oVf6c6kjE0psrMj7tqbWV3QtssEHxw/Qs39ly7I9a+rlMoRGsVPqIUnAJIAvtqUYk0vjkzqBuA4VBCTTDo8N4nT86jLY629Hj+UQuL6ZKe0Nd96CKjvV+U++gkXDb5Y+OlmLOJ8K8h6es8atov+YkUdR8qzNj3F8l5rO1RX2uDHzExsFXMrzK9BcNFhXP2ROE5cQVwRQoKemUb39KCSvDIvA5OOgp9DPt0qBIX1o++FDsD09zbfCHf2pFzM+4xNNJQj4+Q7jPfTdyIiO+fYZ1axy8DY22kMFJwpi66G8Gu9rWBkQv7+BjylXik=
